"use client";

import { jsPDF } from "jspdf";

interface DownloadReportProps {
  documentData: {
    company_name?: string | null;
    report_year?: string | null;
  };
  financialData?: {
    revenue?: number | null;
    net_income?: number | null;
    assets?: number | null;
    liabilities?: number | null;
    gross_margin?: number | null;
    profit_margin?: number | null;
    risk_score?: number | null;
    risks?: string[];
  };
  llmData?: {
    executive_summary?: string | null;
    financial_performance_overview?: string | null;
    risk_analysis?: string | null;
    trend_detection?: string | null;
    investment_recommendation?: string | null;
    red_flags?: string[];
    confidence_score?: number | null;
    compliance?: {
      ifrs_mentioned?: boolean;
      gaap_mentioned?: boolean;
      esg_mentioned?: boolean;
    };
  };
}

export default function DownloadReport({ documentData, financialData, llmData }: DownloadReportProps) {
  const getSafeName = () => (documentData.company_name || "report").replace(/[^a-zA-Z0-9]/g, "_").slice(0, 30);
  const formatCurrency = (n: number) => {
    if (n >= 1e9) return `$${(n / 1e9).toFixed(2)}B`;
    if (n >= 1e6) return `$${(n / 1e6).toFixed(2)}M`;
    return `$${n.toFixed(2)}`;
  };

  const generatePDF = () => {
    const doc = new jsPDF("l", "mm", "a4"); // Landscape
    const width = doc.internal.pageSize.getWidth();
    const height = doc.internal.pageSize.getHeight();
    const company = documentData.company_name || "Company Name";
    const year = documentData.report_year || "N/A";

    const colors = {
      primary: [14, 165, 233],   // #0ea5e9
      secondary: [15, 23, 42],   // #0f172a
      accent: [99, 102, 241],    // #6366f1
      positive: [5, 150, 105],   // #059669
      negative: [220, 38, 38],   // #dc2626
      muted: [100, 116, 139],    // #64748b
      bg: [248, 250, 252]        // #f8fafc
    };

    // Helper: Add Slide Header
    const addHeader = (title: string, subtitle?: string) => {
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, width, height, "F"); // Reset background

      // Header Bar
      doc.setFillColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
      doc.rect(0, 0, width, 24, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(255, 255, 255);
      doc.text(title, 15, 16);

      if (subtitle) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(200, 200, 200);
        doc.text(subtitle, width - 15, 16, { align: "right" });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(colors.muted[0], colors.muted[1], colors.muted[2]);
      doc.text(`${company} | FY ${year} | Generated by AI Financial Intelligence Platform`, 15, height - 8);
    };

    // Helper: Add Bullet Points with Pagination
    const addBullets = (text: string | null | undefined, x: number, startY: number, maxWidth: number) => {
      if (!text) return startY;
      doc.setFontSize(12);
      doc.setTextColor(50, 50, 50);
      const lines = doc.splitTextToSize(text.replace(/\*\*/g, ""), maxWidth);

      let y = startY;
      lines.forEach((line: string) => {
        if (y > height - 20) {
          doc.addPage();
          addHeader("Continuation");
          y = 40;
        }
        doc.text(line, x, y);
        y += 7;
      });
      return y;
    };

    // Slide 1: Cover
    doc.setFillColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
    doc.rect(0, 0, width, height, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(36);
    doc.setFont("helvetica", "bold");
    doc.text("Investor Intelligence Report", width / 2, height / 2 - 20, { align: "center" });
    doc.setFontSize(24);
    doc.setFont("helvetica", "normal");
    doc.text(company, width / 2, height / 2, { align: "center" });
    doc.setFontSize(16);
    doc.text(`Fiscal Year ${year}`, width / 2, height / 2 + 20, { align: "center" });
    doc.setDrawColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    doc.setLineWidth(1);
    doc.line(width / 2 - 50, height / 2 + 30, width / 2 + 50, height / 2 + 30);
    doc.setFontSize(10);
    doc.setTextColor(180, 180, 180);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, width / 2, height - 15, { align: "center" });

    // Slide 2: Executive Summary
    doc.addPage();
    addHeader("Executive Summary", "Key Highlights");
    addBullets(llmData?.executive_summary, 15, 40, width - 30);

    // Slide 3: Financial KPIs Dashboard
    doc.addPage();
    addHeader("Financial Performance", "Core Metrics");
    const kpis = [
      { label: "Revenue", val: financialData?.revenue, fmt: formatCurrency },
      { label: "Net Income", val: financialData?.net_income, fmt: formatCurrency },
      { label: "Assets", val: financialData?.assets, fmt: formatCurrency },
      { label: "Liabilities", val: financialData?.liabilities, fmt: formatCurrency },
      { label: "Profit Margin", val: financialData?.profit_margin, fmt: (v: number) => `${v}%` },
      { label: "Risk Score", val: financialData?.risk_score, fmt: (v: number) => v.toString() }
    ];

    let kpiX = 20;
    let kpiY = 40;
    kpis.forEach((k, i) => {
      // Card Box
      doc.setFillColor(245, 247, 250); // Light gray
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.5);
      doc.roundedRect(kpiX, kpiY, 70, 40, 3, 3, "FD");

      // Label
      doc.setFontSize(10);
      doc.setTextColor(colors.muted[0], colors.muted[1], colors.muted[2]);
      doc.text(k.label.toUpperCase(), kpiX + 35, kpiY + 12, { align: "center" });

      // Value
      doc.setFontSize(18);
      doc.setTextColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
      doc.setFont("helvetica", "bold");
      const valText = k.val != null ? k.fmt(k.val) : "—";
      doc.text(valText, kpiX + 35, kpiY + 28, { align: "center" });

      kpiX += 80;
      if ((i + 1) % 3 === 0) {
        kpiX = 20;
        kpiY += 50;
      }
    });

    // Slide 4: Detailed Analysis
    doc.addPage();
    addHeader("Financial Analysis", "Detailed Breakdown");
    addBullets(llmData?.financial_performance_overview, 15, 40, width - 30);

    // Slide 5: Risk Assessment
    doc.addPage();
    addHeader("Risk Assessment", `Risk Score: ${financialData?.risk_score || "N/A"}/100`);
    let riskY = 40;
    if (financialData?.risks?.length) {
      financialData.risks.slice(0, 8).forEach(risk => {
        doc.setFillColor(254, 242, 242); // Red-50
        doc.setDrawColor(252, 165, 165); // Red-300
        doc.roundedRect(15, riskY, width - 30, 12, 1.5, 1.5, "FD");

        doc.setFontSize(10);
        doc.setTextColor(153, 27, 27); // Red-800
        doc.text(`• ${risk}`, 20, riskY + 8);
        riskY += 16;
      });
    } else {
      doc.text("No specific risks identified.", 20, 50);
    }

    // Slide 6: Red Flags
    if (llmData?.red_flags?.length) {
      doc.addPage();
      addHeader("Critical Red Flags", "Attention Required");
      let flagY = 40;
      llmData.red_flags.forEach(flag => {
        doc.setTextColor(220, 38, 38);
        doc.setFontSize(16);
        doc.text("!", 15, flagY);
        doc.setTextColor(50, 50, 50);
        doc.setFontSize(12);
        doc.text(flag, 25, flagY);
        flagY += 12;
      });
    }

    // Slide 7: Trend Detection
    doc.addPage();
    addHeader("Trend Detection & Outlook");
    addBullets(llmData?.trend_detection, 15, 40, width - 30);

    // Slide 8: Investment Recommendation
    doc.addPage();
    addHeader("Investment Recommendation");
    addBullets(llmData?.investment_recommendation, 15, 40, width - 30);

    // Slide 9: AI Transparency
    doc.addPage();
    addHeader("AI Analysis Transparency");
    doc.setFontSize(14);
    doc.setTextColor(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
    doc.text(`Confidence Score: ${Math.round((llmData?.confidence_score || 0) * 100)}%`, 20, 50);
    doc.setFontSize(12);
    doc.setTextColor(colors.muted[0], colors.muted[1], colors.muted[2]);
    doc.text(`Analysis Engine: Groq Llama-3 70B`, 20, 65);
    doc.text(`Validation Status: ${llmData?.confidence_score && llmData.confidence_score > 0.7 ? "Verified High Fidelity" : "Standard Review Check"}`, 20, 75);

    // Save
    doc.save(`${getSafeName()}_Investor_Deck_FY${year}.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      className="inline-flex items-center gap-2 rounded-lg bg-slate-800 px-4 py-2 text-sm font-medium text-white transition hover:bg-slate-700 dark:bg-slate-700 dark:hover:bg-slate-600 shadow-sm"
    >
      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      Download Investor Deck
    </button>
  );
}
